---
core:
  # server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
  server_url: https://fcps-dev.kinops.io
  space_slug: fcps
  space_name: Fairfax Country Public Schools
  service_user_username: brian.peterson@kineticdata.com
  service_user_password: Kinetic235
options:
  delete: false
task:
  # server_url: https://<SPACE>.kinops.io/app/components/task   OR https://<SERVER_NAME>.com/kinetic/kinetic-task
  server_url: https://fcps-dev.kinops.io/app/components/task
  service_user_username: brian.peterson@kineticdata.com
  service_user_password: Kinetic235
http_options:
  log_level: info
  log_output: stderr
